### ISSUE TITLE
Couldn't run tutorials

### ISSUE THREAD

**Issue by oguzhancebe** [humanoid-path-planner/hpp_tutorial#10]
Hello,

During installation,  I did `sudo apt-get install pr2-indigo-*`, because `sudo apt-get install pr2-indigo-desktop` or `sudo apt-get install pr2-indigo-robot` returns `E: Unable to locate package`. Nevertheless, I can run pr2 on Gazebo.

I started tutorials, Step 1 and Step 2 is ok, but when I can't run any python scripts in `src/hpp_tutorial/script`. In tutorial_1,  I get the output attached as .txt.
[tutorial_1_output.txt](https://github.com/humanoid-path-planner/hpp_tutorial/files/1333430/tutorial_1_output.txt)

I tried `debug.py`, it launches gepetto-viewer with an object. The image is attached
![gepetto_screenshot1](https://user-images.githubusercontent.com/29755707/30865082-85e7f55c-a2cd-11e7-8cfc-049217f4dc12.png)

tutorial_2.py returns the following error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oguz14/hppdev/install/lib/python2.7/site-packages/hpp/corbaserver/problem_solver.py", line 478, in selectPathPlanner
    return self.client.problem.selectPathPlanner (pathPlannerType)
  File "/home/oguz14/hppdev/install/lib/python2.7/site-packages/hpp/corbaserver/problem_idl.py", line 285, in selectPathPlanner
    return _omnipy.invoke(self, "selectPathPlanner", _0_hpp.corbaserver.Problem._d_selectPathPlanner, args)
hpp.Error: hpp.Error(msg='No path planner with name PRM')

Can you help me about this?

**Comment by florent-lamiraux** [comment]
Dear oguzhancebe,

Which version did you select to download on page "Download and install" ?
It seems that you did not choose "stable".

Can you cd in hpp_tutorial, type git log and send the output ?

**Comment by oguzhancebe** [comment]
The output is:
commit 3adfe3ffbf0d5b5bae25cf5b711ee425dfd449f7
Author: Joseph Mirabel <jmirabel@laas.fr>
Date:   Wed May 31 22:12:42 2017 +0200

Update tutorial_manipulation.py

commit de1e34b22144a8a5fc205b622b1f088f191e9c8a
Author: Joseph Mirabel <jmirabel@laas.fr>
Date:   Wed May 17 15:00:57 2017 +0200

Force Python 2.7 and synchronize CMakeLists.txt

commit 69d07fefce36cbaac6cec461ba1373029ef430d6
Author: Florent Lamiraux <florent@laas.fr>
Date:   Wed Feb 15 17:10:27 2017 +0100

Update scripts and documentation to pinocchio version of HPP.

commit 8e1e09e00ab74b50b1abfc4664a9c17c4559daf5
Merge: fa99098 91ba20c
Author: Florent Lamiraux <florent@laas.fr>
Date:   Wed Feb 15 16:22:10 2017 +0100


In "Download and Install, Stable is selected(this is also by default), but the installation steps are:
`wget -O $DEVEL_DIR/config.sh https://raw.githubusercontent.com/humanoid-path-planner/hpp-doc/master/doc/config.sh`
`wget -O $DEVEL_DIR/src/Makefile https://raw.githubusercontent.com/humanoid-path-planner/hpp-doc/master/doc/Makefile`

I might change 'master' to another branch in these steps, but I don't know which one is stable.

**Comment by florent-lamiraux** [comment]
It seems that you ran "tutorial_1_roadmap.py" which is outdated. We should either update it or remove it.
Can you try to run "tutorial_1.py" instead ?

tutorial_manipulation.py should work as well, but you need to run "hpp-manipulation-server" instead of hppcorbaserver.
